### PR TITLE
New shot detection

### PR DESCRIPTION
**Pull request by cbdmaul**
I'm probably supposed to put something useful for you here.

Here's a recipe for meatloaf:

```
Preheat oven to 350 degrees F (175 degrees C).
In a large bowl, combine the beef, egg, onion, milk and bread OR cracker crumbs. Season with salt and pepper to taste and place in a lightly greased 5x9 inch loaf pan, OR form into a loaf and place in a lightly greased 9x13 inch baking dish.
In a separate small bowl, combine the brown sugar, mustard and ketchup. Mix well and pour over the meatloaf.
Bake at 350 degrees F (175 degrees C) for 1 hour.
```

### CODE REVIEW

**Comment by phrack** [comment]
Before I review this (probably in a few days), are the following boxes checked?
- Users can turn on and off shot detection by sector
- The places to put warnings are known and preferrably marked with a // TODO: comment (which most Java IDE's will put in a task list for us for easier tracking)
- The new test videos are present (i.e. all unit tests are runnable even if they don't pass)
- There aren't any problems with the test cases outside of those that trivially fall under #218 (e.g. missed shots that are not reasonably detectable without adding a lot of noise are clearly marked)
- Autocalibration works or its dependencies have been removed (if the autocalibration code isn't really there I'd prefer to remove the gigantic dependencies until it is)

**Comment by cbdmaul** [comment]
1. Yes, and I tested it last night
2. For some brightness cases and motion, there are functions in CameraManager waiting for code
3. They are not present yet.  I need to convert them.
4. I didn't change the test cases because I think the tests should be refactored.  The x/y of shots is going to move around based on tweaks to the shot detection and I'm not going to waste my time changing 30 testcases every time.
5. I forgot to remove the dependencies for that, so build.gradle should be updated.

**Comment by phrack** [comment]
I'll wait for 3 and 5 to happen before trying to merge. For 4, I meant if there are shots you know you don't want to even try to detect have you marked them? I am asking this because when I go to refactor tests I want to know which shots those are so that I can acknowledge them without causing test failures. We need to do this because if we add continuous integration, which I would like to after 3.4, we will never get a nightly build if tests are failing due to shots we know we don't care about detecting.

Given that you pulled from master already, I think this merge should be pretty smooth.

**Comment by cbdmaul** [comment]
I will do 3 and 5 tonight.

For 4, I have not marked any of the shots in the new testcases, only the count and color.  How about if I clean up one test file for you to refactor and leave the rest for after the refactoring is done? Then I can just edit them to match the right way the first time.

I think the refactoring should include continue on errors for test cases, it would make it much easier to tweak / refine shot detection in the future.

By the way, you should test what I have now because I fixed a bug which forced me to change the shot detection threshold for cluster connectedness.  I based the change on the test case results not any real world testing.  Make sure there aren't any new unexpected false negatives (missing shots).  It is easy to fix if it is.

**Comment by phrack** [comment]
I think I am being unclear. My question is, are there any assert blocks like this:

```
    assertEquals(626.0, shots.get(0).getX(), 1);
    assertEquals(168.5, shots.get(0).getY(), 1);
    assertEquals(Color.RED, shots.get(0).getColor());
```

that fail not because a shot has moved a bit or has the wrong color, but because we flat out won't be detecting it because it's too small or whatever. If those are marked (e.g. via a comment saying something like "used to detect this but it's too small; if we detect this noise will get through too") I'd like to handle them in the following way:

Check for them as an "optional" shot. If they are detected, awesome, do nothing. If they are not detected, emit a test warning saying the shot was not detected, but it was optional anyway. This would let us continue to test for them in case some super amazing future algorithm can get them, but without them causing failures.

For non-optional shots, I agree. We should collect all of the missed shots and fail only after all of the asserts so that we have the full picture of what's wrong.

I will be sure to test before merging.

**Comment by cbdmaul** [comment]
I think that behavior is fine.  That actually sounds very good.

What I'm saying is, that right now the tests have not been adjusted for coordinates at all.  Most do not have shots marked, only the count and color.  The reason is I never bothered to do it because I knew we wanted to refactor testing.  What I am saying is, if there's one in particular that you want to redesign how you are describing, I will make that one have the comments you are describing.  But doing all of them is counter productive because they'd have to be redone AGAIN afterwards.

By the way, I added the ability to take pictures of accepted shots.  That's how I was verifying correct shot detection without having the test check the coordinates.  It is much more useful for shot detection design.

**Comment by phrack** [comment]
I see, makes sense. I'd add coords for at least one. My basic plan was:
1. Create a list of required shots, their base coords, and their colors.
2. Create a list of optional shots, their base coords, and their colors.
3. Check for all required shots using fuzzy locations (e.g. shot can be anywhere within 5 pixels of the base coords) and collect all failures until we get through the full list. Order of shots won't matter, just that they were seen or not.
4. Same thing as 3 but just a warning instead of a failure.

What I did to get coords before was just put a for loop before any assert to print out all of the detected shots. I don't have it on this computer, but I had a 4 line loop that printed out the assert blocks for every single shot that was actually detected. I also printed out images for each shot. Assuming the pictures looked right, I'd just copy and paste the printed out assert blocks as the new test. This was WAAAAAY faster than manually changing things.

**Comment by phrack** [comment]
PS. Given what you have it's fair to not change any of the tests as well (assuming my understanding is right). I will generate most of the code anyway. I was just concerned that there would be an assert block for a shot that isn't in the detected shot list at all and I wouldn't know if it was intentionally ignored (e.g. because it was too small) or if it is a legitimate problem.

My overall vision for the refactored test is that there will be a base "ShotDetectionTester" class with methods to check for required shots and collect errors and check for optional shots to generate warnings. Each unit test class (we have 5 now I think) for shot detection will extend this base class to use those methods. The tests themselves will just be adding required and optional shots to their respective lists to be checked in the base class against what was actually detected.

**Comment by cbdmaul** [comment]
Yes, that's exactly how it is right now.  I did not do anything to the tests.

If you could automatically generate them off the tests, I can go through and verify them against the shot photos and add the optional ones we're currently missing.

**Comment by phrack** [comment]
OK, that sounds perfect. Let's go ahead and call checkbox 4 checked and I'll merge after you check 3 and 5 and I test.

I'll refactor the tests in #218 and you'll double check them and add optional shots to close it.

**Comment by cbdmaul** [comment]
2, 3, 5 done

I refined what happens for 2.  You will notice that bright pixels turn red when the brightness threshold is met.  since we don't have an overlay yet, the functions in cameramanager are called but you might not know your brightness/motion is too high (Although the pixels do turn red for brightness).  That's my warning for you doing any testing right now.

**Comment by phrack** [comment]
Spent 30 minutes with it today.

A. The bouncing targets exercise is unusable even with my projector brightness all the way down. It gets green false positives from the gray targets, but red targets seem fine. I'd say the gray color just needs to be changed, but it's weird that it happens even with the brightness all the way down.

B. Attached a picture of a bizarre calibration issues. This happened on about the 5th calibration. Basically behind the label turned gray then if I moved the calibration target other random areas of the feed would go gray too. Never had this one before! I got no exception and stopping and restarting calibration didn't fix it. I had to restart ShootOFF in the end to fix it.

screenshot from 2015-09-30 17-45-35

C. This may not be just your branch but I got this NPE while deleting targets on the arena:

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
    at com.shootoff.gui.CanvasManager.lambda$1(CanvasManager.java:124)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
    at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:352)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$355(GlassViewEventHandler.java:388)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:387)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$50(GtkApplication.java:139)
    at java.lang.Thread.run(Thread.java:745)

**Comment by phrack** [comment]
I should say outside of these issues it was flawless.

**Comment by cbdmaul** [comment]
I don't know if it is causing B but I could see a calibration related issue where the shotdetectionmanager is applying the wrong data to pixels because it is blind to the calibration: it is only passed what it needs to work on.  So if the data in shotdetectionmanager isn't reset when calibration is changed then it will be operating on the wrong data.  Of course it should only take a second to adjust anyway.  It's worth looking into.

**Comment by phrack** [comment]
It'd be interesting if that is what is causing B. I will say that essentially every time I calibrate after the first time it's because I moved something (mostly me bumping my fucking camera), thus the old data would no longer be relevant anyway. When I got this issue I was trying to shoot in a really cramped area of my living room and kept bumping the camera. About 5th or 6th time I was recalibrating because the camera moved I got B.

**Comment by cbdmaul** [comment]
Also worth mentioning, the shot detection does not change the frame at all (With the exception of red for brightness).  So the bug would have to be in cameramanager not shotdetectionmanager.

Maybe it is not so much a bug as something we've never had to consider before? Since I don't change the frame, if the GUI control is just working off an updated frame instead of a new frame, maybe it is not wiping the empty areas of the control?

**Comment by phrack** [comment]
It'd be hard to say without seeing pictures of precisely what the camera saw when a shot was detected, but I kind of wonder if A and B are related. A is far more important because it makes a current exercise unusable and it makes some of our future plans impossible (e.g. shotgun training). Having said that, maybe a refresh isn't happening fast enough so when the target moves there is a small white spot and gray + white spot (maybe with some grass from the background I had on at the time) ends up being detected as a green shot?

**Comment by cbdmaul** [comment]
They shouldn't be related unless you are recalibrating during an exercise.

Edit: If the reason for the bug is what I suspect.  All bets are off otherwise.

**Comment by cbdmaul** [comment]
A:  Try newest version.  Works for me with lower motion / no background.  Still has trouble with other backgrounds / more motion.  Try it with a dimmed shot target.

I have not seen B or C

**Comment by phrack** [comment]
Whatever you did seems to make a bigger difference than you thought it would. I am not really have any problems with bouncing targets now. I've had a few missed shots on grass, but I am also having kind of stupid environmental conditions (including a lit candle in the frame) and aside from those few missed shots that weren't even on targets it's been fine. I tried replacing the gray shoot target with blaze orange and that seemed OK too. Finally, I temporarily changed the IPSC target to solid blaze orange so that I could observe what would happen on a non-moving target. It got the color wrong about half the time, but I was expecting that.

I think C is a more general issue and will open a bug to add an extra check so we can ignore that. Have not observed B again.

**Comment by phrack** [comment]
PS. Any reason this isn't mergable or should I go for it?

**Comment by cbdmaul** [comment]
I just pushed some additional fixes / tweaks.  I suggest giving it a try before merging.

EDIT: ignore this, did not see your comment.  ~~I'd suggest trying bouncing targets with a lower brightness image as well.~~

If you are happy with it right now, go ahead in merge.  I do not plan to commit again unless you give me the go ahead on something bad happening.

**Comment by phrack** [comment]
OK will try it once I reply to a few more emails. Also, I did some more careful measurements. You're clocking in at 4.87x (so we'll call it 5x) faster now.

**Comment by phrack** [comment]
Crash:

Exception in thread "Thread-7" java.lang.ArrayIndexOutOfBoundsException: Invalid coordinates.
    at java.awt.image.SampleModel.getDataElements(SampleModel.java:367)
    at java.awt.image.Raster.getDataElements(Raster.java:1500)
    at java.awt.image.BufferedImage.copyData(BufferedImage.java:1493)
    at com.shootoff.camera.ShotDetection.ShotDetectionManager.deepCopy(ShotDetectionManager.java:193)
    at com.shootoff.camera.ShotDetection.ShotDetectionManager.processFrame(ShotDetectionManager.java:212)
    at com.shootoff.camera.CameraManager$Detector.processFrame(CameraManager.java:469)
    at com.shootoff.camera.CameraManager$Detector.streamCameraFrames(CameraManager.java:406)
    at com.shootoff.camera.CameraManager$Detector.run(CameraManager.java:353)
    at java.lang.Thread.run(Thread.java:745)

**Comment by phrack** [comment]
Can't get past that crash. I have absolute insane conditions now in the frame (tv on, candle lit, lamp on right by projector), but I won't hold that against the detection algorithm as long it doesn't crash.

**Comment by cbdmaul** [comment]
Fixed it.

Also forgot to commit a file for the testcase FPS estimation, that's in there too now.

**Comment by phrack** [comment]
Still testing. Anyway, see this?

screenshot from 2015-10-02 18-36-20

Got every... single... shot... with this shit.

**Comment by cbdmaul** [comment]
I'm worried that the newscaster appears to be turning into the terminator.

**Comment by phrack** [comment]
He terminates logic and reason.

**Pull request merged**
