### PR TITLE
Working autocalibration

### PR DESCRIPTION
**Pull request by cbdmaul**
Needs minor tweaks to user flow and some UI changes.

### CODE REVIEW

**Comment by phrack** [comment]
Please stand by, I want to figure out why Travis is saying the tests are crashing and burning (some of the messages are unexpected...).

**Comment by phrack** [comment]
Looks like test.properties needs to be restored to its original condition because TestConfiguration testDefaults is failing. That seems to be the only thing keeping this from passing as far as I can tell.

**Comment by cbdmaul** [comment]
test.properties isn't changed?

**Comment by phrack** [comment]
The problem actually appears to be two fold:
1. shootoff.properties doesn't match what's in master (it has erroreporting set to false).
2. In Configuration.java line 114 is set to false in the branch but it's true in master (this defaults errorreporting to true in master even if there is no config file).

**Comment by cbdmaul** [comment]
oh yeah because of the sentry issues.  i'll fix it

**Comment by phrack** [comment]
This is actually showing a huge win for CI and our unit tests. This could have easily slipped through!

**Comment by cbdmaul** [comment]
Don't break your arm jerking yourself off

**Comment by phrack** [comment]
But dat test coverage.

**Pull request merged**
