### PR TITLE
Trapwithskeet_V2

### PR DESCRIPTION
**Pull request by ifly53e**
This projector exercise randomly throws an orange clay pigeon target from the trap house at the center of the screen.  The exercise can also play Skeet by throwing two targets from the sides that come close to crossing near the middle of the screen.  Hit the target/targets as quickly as possible to move to the next randomly thrown clay pigeons.
The targets will disappear after they have completed their flight.  You can scale the clay pigeons to be bigger or smaller.  Scoring:  Hit targets are scored three points per hit.  A target that is not hit is minus 1 point.  All misses are minus 1 point.

### CODE REVIEW

**Comment by phrack** [comment]
Nice changes! I'll put it on my list to test this tonight.

**Comment by phrack** [comment]
Would you mind checking out:

https://github.com/phrack/ShootOFF/pull/368#issuecomment-190308981

and

https://github.com/phrack/ShootOFF/wiki/Tutorial%3A-Creating-a-Simple-Training-Exercise

We are likely releasing ShootOFF 3.7 in the less than 24 hours with the new modular plugin system. You may be better off using it if that thread and the wiki convince you.

**Comment by ifly53e** [comment]
I was hoping to get this in before the module implementation.  If this Trap/Skeet moving target exercise closes either the "duck hunt" or DOS shooting gallery issue it should be included as part of the main code.  If it does not, then it should be a module.  

I think adding modules is a good idea but downloading and installing them separately with any extra steps for the user will unnecessarily add technical complications for non-technical people.  Maybe the compromise is for modules to be submitted to the devs for inclusion in point releases.  If the exercise menu gets too long then turning modules on and off via a configuration menu may also be an option.  At least the user will not have to go outside of the program to install additional modules this way.  This also takes away the requirement to host the modules separately anywhere.  It also takes away the requirement for external connectivity for updates while using the program.  Maybe you wait and see how many modules come in before deciding what to do?

Just my thoughts...

**Comment by phrack** [comment]
The new info is that we are pivoting in the release of 3.7 and are moving the motion fix to 3.8 and plugin modules to 3.7. The difference is that the motion bug is not done and is dragging on and on but modules are at least usable by technical users. This allow us to release 3.7 within the next 24 hours instead of potentially weeks from now. My concern is that if we include this in 3.7 now we will have two exercises that are flaky due to the motion bug instead of just one.

We already get a lot of exercise submissions, but most people just email them to us and disappear when we say we can't accept code submissions via email (I don't think any open source project does now days). I am definitely open to comments and alternative ideas that work within our existing context: there are 2-3 unique exercises that come our way a week (this will likely skyrocket when we have native shot detection) and many of our users are effectively computer illiterate.

**Comment by ifly53e** [comment]
That is new info.  I agree that until the motion bug is fixed, putting in a motion based exercise is not prudent at this point.

I could use a github tutorial (desktop version please but could use the command line as well) specific to the ShootOFF project similar to the gradle wiki page.  That would probably also help the email and disappear issue.  This is my first time seriously using github and it has been frustrating for me.  The github tutorials did not help me very much and I would have liked to have a place to have my questions answered from the devs themselves.

A developers forum (either hosted by you or on reddit) specific to ShootOFF would be nice so that coders could upload their idea / exercise / code snippet to the forum for others to help with.  I was using reddit messaging to get some coding questions answered by you (because I did not see other coding questions on the reddit board) but would have preferred to have a forum to search to see if others already had their same specific question answered (the current wiki helps in a general way).  If the intent was always to use reddit in this manner, then I did not happen to get that vibe from the available documentation and wiki.  

I enjoy working on exercises and have more ideas I would like to code for my own use.  This is the first framework that lets me make the exercises I want to actually train with myself so keep up the good work.  The side benefit is that other shooters with similar interests would probably like to use them too and sharing is good motivation for continuing to code.

**Comment by phrack** [comment]
I've added writing a wiki page on making a first contribution via GitHub to the pipeline:

https://github.com/phrack/ShootOFF/issues/393

For now, I am comfortable with using the existing subreddit for dev talk because it's not high traffic, but agree that we haven't really pointed out that it's welcome. No point in having two subreddits that get a post a week (often by me).

Please (constructively) complain early and often. If it wasn't for people giving this kind of feedback ShootOFF would be much worse off.

**Comment by phrack** [comment]
Let me know if you are having trouble converting this to a modular plugin. I should be able to help tomorrow.

**Comment by ifly53e** [comment]
I have not tried to go modular yet.  I scanned the tutorial and I thought
to myself that I do not know how to make a jar file in eclipse...Did you
get that detailed in the instructions?

**Comment by ifly53e** [comment]
Ok, so I re-read the wiki on creating a training exercise and the tutorial.  So, after every change I make in my java file, I have to run "gradle jar" and copy the resulting jar file to the exercises folder and then run the debugger?  If this is the case, it appears that additional steps have been added for tweaking java exercise files instead of making the change and running the debugger directly.  I suppose that a batch file could be produced to combine some steps but it appears that developing exercise modules is no longer as easy as it used to be...am I off here?

**Comment by phrack** [comment]
The sample gradle script does everything you need to build and package. You actually shouldn't need to change any code, it should just be a matter of re-organizing the filesystem layout of the project (match the example one), creating the shootoff.xml file, and running: gradle jar. From there, copy and and paste the JAR into your main ShootOFF install's exercises directory.

**Comment by phrack** [comment]
PS. If there is any problem it will be loading the targets from a resouce, which is a bridge we can cross when the rest is laid out.

**Comment by ifly53e** [comment]
Phrack,  is there a mechanism to compile, run, and troubleshoot exercise
java files and stay entirely within the eclipse ide similar to developing
exercise files for 3.6?  Does that already exist or is getting out of the
ide, running gradle jar from the command line,  copying the file to a
separate directory, and then back to the debugger the only way to develop
exercise files now?

**Comment by ifly53e** [comment]
Ok...I figured out that registering the exercise moved from shootOffController to pluginEngine so I just registered my developmental exercise in pluginEngine manually.  Crisis averted...

**Comment by phrack** [comment]
It would also be pretty easy to extend the gradle file to build and jar the exercise, copy it for you to your install of ShootOFF, and start ShootOFF with one command. Gradle is extremely powerful, the tutorial is just the bare bones basics.

**Comment by ifly53e** [comment]
I don't have a an issue using gradle after I am done troubleshooting and I think my exercise is finished and it is time to create a module...it just rubbed me the wrong way when I thought I had to go through all of these steps when I am changing code during the developmental process.

**Comment by phrack** [comment]
Yea, point was just that you don't really have to put up with it during the development process even without ShootOFF modifications. Just gotta extend the build script a bit.

**Comment by ifly53e** [comment]
Do you all use gradle scripts to troubleshoot your code?  Maybe I am doing things the hard way...

**Comment by phrack** [comment]
Usually we use unit tests and check fine grained data points. This is faster than running all of ShootOFF, plus you have a test you can always run later when  refactoring.

**Pull request closed without merging**
