### PR TITLE
Added ParForScore drill. All 109 existing JUnit tests pass.

### PR DESCRIPTION
**Pull request by edwardkort**
I didn't see an exported formatter.xml. So the GitHub diff will show a low of irrelevant white-space differences.

### CODE REVIEW

**Comment by phrack** [comment]
Will have to decide the best way to do the pause/resume buttons. My initial reaction is that it doesn't make sense for them to be two different buttons or up 100% of the time. My instinct at the moment is to dynamically add them if they don't exist using the training exercise API then remove them when the training exercise plugin is destroyed (in the API's destroy method). This would ensure they are only present for exercises that actually use them.

I have this in a branch right now and need to play with it more later. Since I have it in a branch I can play with the code pretty easily.

**Comment by phrack** [comment]
I see why pause/resume were separate buttons now. I still think they should only be dynamically added when necessary and destroyed when no longer needed.

In any case, the much bigger problem for me is the whitespace changes. For some reason the use of spaces/tabs became SUPER inconsistent, thus making the formatted code very wonky in a default configuration of Eclipse. I can probably do the rest if you can back out the whitespace changes. It'd be better to fix the formatting in a separate change because mixing functional changes with whitespace changes is making the diffs insane (good god ShootOFFController.java...).

**Comment by edwardkort** [comment]
Yes, GitHub's diff is really white-space stupid. I have found that the best way around this is to provide a project-standard format. If you go into the Project->Properties->Java Code Style->Formatter, and press the Export All button, an XML file will be created with all your formatting standards. Check this into the project. Then anyone can import these standards. A simple Ctrl-Shift-F will then format the file without white-space variation.

If you create the XML file, I'll reformat the 10 files in the fork and check them in.

**Comment by phrack** [comment]
Thanks for the tip, that taught me something new. I just pushed formatter.xml with my preferred settings to origin/master. The profile name is "ShootOFF".

**Comment by edwardkort** [comment]
In regard to the JavaFX threading (my insertion of the SwingUtilities call), I would guess that the underlying thread queues are the same whether a JavaFX or Swing app.

At least on my system, I was seeing an asynchrony in the score writing of the Shoot for Score drill. Very often, the score is not written until the next shot is posted (with or without a score). The SwingUtilities call cured that. Whether there is a comparable Platform call, I don't know: I've never used JavaFX.

**Comment by edwardkort** [comment]
The display and behavior of the Pause/Resume buttons was just the simplest Band-Aid for stopping the beeps in TimedHolsterDrill when I wanted to look at the shot table. I agree, when timing is not involved, those buttons make no sense.

**Comment by edwardkort** [comment]
In regard to formatting, you might want to make it SOP that all files are reformatted (Ctrl-Shift-F) with your format standard, before any check-in. Some programmers type in their preferred white space, never using the format capabilities of Eclipse. I am at the opposite end: I never type in optional white space while coding - I just periodically hit the format key combination. Got into that habit way back in the XEmacs days.

If that is an issue in your current codebase, you might want to consider reformatting and pushing the existing code.

**Comment by edwardkort** [comment]
Reformatted and pushed changed java files according to ShootOFF formatter.xml. Hopefully this makes the diffs useful.

**Comment by phrack** [comment]
MUCH better! I'll go ahead and open an issue to go through and run the formatter on everything and ensure license blocks are present as I am sure we need to reset those baselines.

My todo list for this PR is the following:
1. (DONE) Figure out what to do about Platform.runLater/SwingUtils.invokeLater.
2. (DONE) Create methods in the protocol API to add arbitrary buttons with custom event handlers (passed in as Lambdas) next to the Reset button, and remove them when destroy is called. This will solve both the "buttons aren't always relevant" and "event handler overloading is wonky" issues.
3. Update wiki to document new protocol and the buttons.

I have a camera sitting on my desk I _really_ need to get to testing, but I can probably burn through these pretty quick once that is done.

**Comment by edwardkort** [comment]
Excellent. Thank you.

I would suggest a fourth task. I don't know how many new drills, extending existing ones, you envisage. But creating the ParForScore drill should have entailed very few lines of code. However, the inner classes of its parent required a lot of copy/paste, a "code stink" in Agile parlance. Perhaps a different design pattern for these inner classes is appropriate.

I see this as a natural process in Agile development. Always architect code that does only what is required now. As those requirements change, refactor the code to accommodate the changes. Just my two cents.

**Comment by phrack** [comment]
This isn't dead btw. I have made decent progress on the todo list but I haven't finished anything enough to push a commit because there were holiday parties this week I found out about at the last minute (not that I am complaining...).

**Comment by edwardkort** [comment]
Not to worry. I have no expectations, either in regard to time or intent. That's the playing field for open source projects with developer time generously given.

**Comment by phrack** [comment]
This pull request is being opened from my branch as #310

**Pull request closed without merging**
