### PR TITLE
Refactored Camera, CameraManager

### PR DESCRIPTION
**Pull request by cbdmaul**
Another milestone of tests passing

### CODE REVIEW

**Comment by cbdmaul** [comment]
Please look at ProjectorSlide, line 147.  I commented this line out due to CameraManager changes.  Couldn't figure out if the line did anything or not.

**Comment by phrack** [comment]
The camera manager is set for the canvas for two things:
1. So the canvas can implement click-to-shoot.
2. For some camera to canvas and canvas to camea conversion you added (`translateCameraToCanvas` and `translateCanvasToCamera`). Is this conversion still necessary? It's used in `updateBackground(BufferedImage, Bounds)` and `CalibrationManager.calibrate`.

Normally this would be set when a new camera is being added, but it was set when the projector arena was created (the arena has its own canvas) in this case because no camera is created for the projector arena. The quickest way to check for a side effect will be to see if click-to-shoot is now broken if you try to use it on the arena tab.

**Comment by phrack** [comment]
Commenting out ProjectorSlide 147 does indeed break click-to-shoot. I'll add it back with a comment. In the future, you can right click a method or variable and clicked "Open Call Heirarchy" in Eclipse to see where it is used (I should do this with the translate methods...). This is actually one of the lesser reasons I insist on type safety, such as the use of generics in the ItemSelectionPane. When everything is type safe these IDE lookup tools tend to work extremely well.

**Comment by phrack** [comment]
PS. I haven't done any debugging yet, but I never get a camera feed now with these changes. It's just permanently the wait spinner that is supposed to indicate that the camera is loading. I'll open an issue.

**Comment by cbdmaul** [comment]
interesting.  does shot detection work anyway?

**Comment by phrack** [comment]
Will try it in a second. In any case, modifiers like `public` or `abstract` for methods defined in an interface are invalid within the Java language reference (EDIT: They ARE fine in the class that implements the interface). The standard compiler will just silently ignore them, but compilers can throw an error instead.. Will push a fix for the `Camera` interface in a second.

I only recently learned this the hard way, thus you'll see that I defined `public` in some interfaces too.

**Comment by phrack** [comment]
This commit removes the modifiers, makes the CM logger private, and adds back setCameraManager (still causes the NPE I just opened an exception for):

31ead7a5bf50a40c42381a93f4655cedf4b421b3

I made the CM logger private because making it protected will cause CM subclasses (not that we have any...) to appear in a log as the CM. This can be intentional in some cases, but if it isn't intentional it's a bug because it makes the logs confusing.

**Comment by phrack** [comment]
Can confirm that shot detection silently doesn't work. I get this log message even though there seems to be no camera:

2016-09-02 19:15:58 [JavaFX Application Thread] DEBUG com.shootoff.camera.CameraManager - starting camera thread Microsoft® LifeCam HD-3000 /dev/video0

This is the last message I get about a camera. Even doing things that should blatantly get a shot don't produce any further camera-related log messages.

**Comment by cbdmaul** [comment]
that is strange given that tests now use the same mechanism.  an easy test
is to see if the camera thread is running.  the camera thread has here same
name as the camera.  I am wondering if the camera close-reopen thing that
is done for the preferences is messing something up.

**Comment by phrack** [comment]
I just profiled in jvisualvm and there is no shot detection thread. I agree it's probably the open and close for preferences. I get this in my v4l log:

HIGHGUI ERROR: V4L/V4L2: VIDIOC_S_CROP
HIGHGUI ERROR: V4L: setting property #5 is not supported
libv4l2: warning v4l2 mmap buffers still mapped on close()
HIGHGUI ERROR: V4L/V4L2: VIDIOC_S_CROP
HIGHGUI ERROR: V4L: setting property #5 is not supported

Property #5 is probably setting the FPS. This can be ignored because it's harmless and it also reports that things aren't supported even though they are. It also says exposure isn't supported but changing the exposure setting has a non-unexpected (but also not _the_ exactly expected) outcome*.

*This is open source code for "it also seems to fuck with my white balance and my exposure" -- if my statement were correct the first time it wouldn't be open source.

**Comment by cbdmaul** [comment]
I'll diagnose later tonight although this never happened to me.  the camera
open/closed status is very confusing in the code, I really had no idea what
camera manager should do if the camera isn't acting right.  it is notified
that the camera closed, but I didn't know what to do with that information.

**Comment by phrack** [comment]
You should look at the lower level code if you think that's confusing. In OpenCV calling CameraCapture.release() is like waiting for the next scene in a time travel movie. Literally anything can happen. Conway's law strikes again.

I'll try removing the open/close code for preferences temporarily just to see what happens. Will report back.

**Comment by phrack** [comment]
I just fixed it with this commit:

e7dc90e996620ba5dddd2bc166e8d612f450651c

That was a hack for webcam-capture to work around a bug in Mac. It's not relevant with an OpenCV camera. 

I am going to buy a fifth of whiskey before testing this on Mac...

**Pull request merged**
