### PR TITLE
Nordic quick shooting

### PR DESCRIPTION
**Pull request by oluies**
Intenti is to add plugin for NordicQuickShooting

(need suggestions for testcases)

### CODE REVIEW

**Comment by phrack** [comment]
You should make at least two revisions for now:
1. repeatExercise should probably be volatile given that it's used in multiple threads. We didn't do this in a few exercises and had to revise later due to race conditions cleaning up.
2. You should run a code formatter on just the NordicQuickShooting class. formatter.xml in the root of the repository is the profile for Eclipse, but not sure if IDEA can do anything with it.

If you can submit your change to .gitignore as a separate pull request. I'll merge that immediately. Your tests are good enough as a bare minimum, but you might want to consider what failure conditions or "quick outs" there are for this exercise that could lead to a round not being completed ideally.

Finally, you should be away of #366. Aside from the .gitignore change, you may want to keep your own repo and submit a packaged plugin later (we likely aren't accepting more default exercises in general because we already have so many to maintain).

**Comment by oluies** [comment]
Sure, I can move it to to a module as per #366

**Comment by phrack** [comment]
Thanks for closing this and for the comment. FYI, most of the core devs have full time jobs, thus development doesn't always happen during the week. Just wanted you to know we weren't ignoring you.

**Comment by oluies** [comment]
Hi, 

Yes, of course. Same for me but I am unsure if I don’t always work during weekends aswell :) 

Whas there some docs for the module system ? 

Örjan 

-- 
Orjan Lundberg
Sent with Airmail

On 6 February 2016 at 00:18:25, phrack (notifications@github.com) wrote:

Thanks for closing this and for the comment. FYI, most of the core devs have full time jobs, thus development doesn't always happen during the week. Just wanted you to know we weren't ignoring you.

**Comment by phrack** [comment]
Not much yet, hopefully that will change in meaningful ways this weekend.

**Comment by oluies** [comment]
What are you going to use ? Serviceloader ?
https://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html

I did something in rvsnoop earlier, but I think that is removed now
https://github.com/oluies/rvsnoop/tree/master/src/main/org/rvsnoop

Since it is basically scheduling it is about, it might be intresting to use
a scheduler such as quartz?
http://java-source.net/open-source/job-schedulers

Örjan

On Sat, Feb 6, 2016 at 2:05 PM, phrack notifications@github.com wrote:

> Not much yet, hopefully that will change in meaningful ways this weekend.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/phrack/ShootOFF/pull/368#issuecomment-180763421.

## 

SKYPE: orjan_lundberg

**Comment by phrack** [comment]
I was going to use a ServiceLoader, but it can't find new providers a RunTime, thus I'll probably use a timer thread and a URLClassLoader. I want it to be very basic for people making plugins while allowing dynamic exercise registration.

**Comment by phrack** [comment]
Please see: https://www.reddit.com/r/ShootOFF/comments/44iw5n/new_wiki_page_creating_training_exercises/. Note the part about now being the optimal time to complain.

**Comment by oluies** [comment]
Looks great. What is the best way to setup a dependent project in gradle? 
Are you publishing the libs or should we reference with gradle such as
http://stackoverflow.com/a/16999835/203968

**Comment by phrack** [comment]
I am leaning towards the SO answer at the moment. My thought is that you probably want to reference what's in the main ShootOFF repo with gradle, otherwise testing more complicated exercises would basically be impossible.

**Comment by oluies** [comment]
Do you have a template project? I might be able to have a look this weekend otherwise.

**Comment by phrack** [comment]
Nothing much yet. There are test cases here:

https://github.com/phrack/ShootOFF/tree/3.8-dev/src/test/exercises

It would be this for you:

You have com/shootoff/plugins/NordicQuickShooting.class in NordicQuickShooting.jar. You add an xml file called shootoff.xml to the root of the jar with the following contents:

```
<?xml version="1.0" encoding="UTF-8"?>
<shootoffExercise exerciseClass="com.shootoff.plugins.NordicQuickShooting" />
```

You place NordicQuickShooting.jar in SHOOTOFF_HOME/exercises and it just works.

**Comment by oluies** [comment]
Moved here https://github.com/oluies/ShootOFF-Pistol-NordicQuickshooting

**Comment by phrack** [comment]
Awesome! Your installation instructions end with a isometric specific text (unless Nordic Quick Shooting is about strengthening muscles as well). 

One thing I want to think about now is how do we make it easier for regular users to find these types of exercises, install, and use them? One idea is to have some similar take on an Add-On manager like Firefox's. However, instead of hosting the plugins we could have a curated XML or JSON list of addons to pull from. Maybe the data could just be: description of plugin, name, version, download URL, and screenshot. The download URL could just be a link to the JAR file uploaded as a release for the repo. 

This would be relatively simple to do it would also be enough to do auto-plugin updates.

**Comment by oluies** [comment]
N.B have to test this, :)

I like the reference system that SBT/Play 2/Zeppelin uses where you just point to the plugins and then they self update. Might be possible to do something similar if you are using gradle as the launcher? 

Eg host the file in a repository / web dav and then the starter pulls it from the repository. 

see
http://www.scala-sbt.org/0.13/docs/Plugins.html

**Comment by phrack** [comment]
The problem with using Gradle as a launcher is that many of our users are effectively computer illiterate and installing even Java is a barrier. Even more have no idea how to use the command line. Adding another install dependency would probably not be good.

**Pull request closed without merging**
