### PR TITLE
TossUP/CanToss

### PR DESCRIPTION
**Pull request by ifly53e**
Just want to get some feedback...I don't really expect for these changes to be merged to the master but I want to discuss them with the team.

This is probably a good candidate for a 3.8 module.  Targets are "thrown" into the air and come back down.  This was an effort to create a speed drill and partially satisfy the "duck hunt"
issue.

The motion of the targets that are thrown in the air causes false green shots.  I currently ignore green lasers in the preferences.

There is significant lag when targets are moving fast.  I replicated this in bouncing targets as well.  A shot on the trailing edge of the fast moving target will not produce a hit.  To compensate for this, I have an ellipse coupled with the image in the target file so when the user hits the gif on the screen, the lag will show the hit in the ellipse and the user gets credit for it.

To create the "report card of hits" at the end of a round, I needed a way to get the location of the shot when it was found in the hit region
of the target.  This is already done in the canvasManager so I added a regionImpact x and y in the interface of the targetRegion along with
gets and sets so the canvasManager can record the impact coordinates in the TargetRegion.  If the shotListener was provided the Hit instead of
only the targetRegion, this would not be necessary.  My changes only require changes to the regions, not the existing training exercises
(like a new overloaded shotListener would require) so I did not overload the shotListener to return the Hit instead.  Either way, I would get
what I needed.

### CODE REVIEW

**Comment by phrack** [comment]
It would be an easy change right now to add Hit to shotListener. I'll go ahead and add that to 3.7 so that it's released before people start doing a bunch of modules.

The false green shots are because of #329. Our solution to this problem is to create a mask based on what is being projected and factor that out of shot detection. This way you can project all kinds of stuff without it getting too confusing for shot detection. The last several commits in master place almost all of the infrastructure to accomplish that, but it's not quite done yet.

Do you consider adding projector messages to be a requirement? We originally didn't do this because it caused problems with shot detection, but shot detection has gotten _much_ better since those days.

What's up with the grgit code being commented out? I thought it could only cause an issue if you were using the build script outside of a repo, but if it's causing more general problems we should fix them.

Overall, I really like what this exercise is doing and I think it would make sense as a start to a "Duck Hunt" module. Here are things that I think would get this closer to something we can keep working on separately:
- Should get to the point where the exercise doesn't need custom changes to ShootOFF so that it can be its own repository, unless the change can be accomplished with some basic inheritance. I think at least some of what I bring up above gets there.
- Should generally never commit shootoff.properties unless you need to make a permanent change to it that should effect everyone.
- Also should generally not commit commented out/dead code.
- Should replace the targets with animated drawings to make it feel more like a game. Someone else posted a bunch of links to possibilities in the Duck Hunt issue. They wouldn't be coherent enough to feel natural and well polished, but I buy the point that we should just do something to hopefully inspire an artist to help us out.

**Comment by phrack** [comment]
The hit change has been made so you can back all of that out of your fork. You now get a Hit instead of a target region in shotListener. The Hit object holds the target that was shot, the region that was shot, and the shot coordinates adjusted to the region.

**Comment by ifly53e** [comment]
Thanks for adding the HIT change.

I think the projector message is a requirement for two reasons.  First, when playing a game, the score is important to see and a projector message would let the programmer give that to the user.  The second reason is to put a final message on the projector to show the results instead of referring to back to the main program.

I am currently hacking the diagnostic VBox to get the final message on the projector.  Maybe the shootOFF interface can give access to another VBox for a projector message or three?  

I also need access to the projector's arenaController so I made the arenaController available with a get function in ProjectorTrainingExerciseBase.  The arenaController allows the programmer to get to the VBox visible property.  I currently display the projector/diagnostic message at the end when shooting is paused and then make it invisible when shooting starts again.  I also need the arenaController to add and remove the report card shots relative to the targets that were hit.  Lastly the arenaController lets me add a projector background programmatically instead of a user having to select one every time they run the exercise.

More along the lines of a duck hunt game, I have a Trap shooting exercise finished that implements an exploding gif of a clay pigeon which is more in line with what you are looking for from an artisic view point.  The lag makes it difficult to hit the smaller faster target though so I was hoping when the green shot issue gets fixed, it would free up some processing time to reduce the lag I talked about earlier.

**Comment by phrack** [comment]
I am not really thrilled about exposing the projector arena controller to plugins because it encourages more coupling. If we let plugins couple to things beyond the API we may make it much harder in the future to make non-breaking changes (I am perfectly OK with breaking changes for now, but after 3.8 we likely want to avoid them). In other words, I think we probably want the message to be, "If you use the API, things will stay stable or will at least be easy to refactor if we make a breaking change. If you use more than the API you do so at your own risk and we could easily break things on you with every release."

That said, we should figure out how to support your needs within the context of the plugin API. For messages, it seems like we could make messages on the arena work just like messages on the webcam feeds. In fact, I propose simply overriding showTextOnFeed in ProjectorTrainingExerciseBase to set the message on every feed as it is done in TrainingExerciseBase but to also add the message to the top left corner of the projector arena. I can also add an overloaded version just for projector exercises to set the background color of the projector's label and the foreground color for the font. How does that sound? I can probably have that done real quick and in 3.7 if you agree.

Regarding the report cards, why not add a target's report card directly to the target's group? This would have the nice side-effect that the API will automatically clean them up for you instead of you having to do it yourself. It also doesn't require access to anything beyond what a typical exercise already has access to.

**Comment by ifly53e** [comment]
That is a good start.  I had to change the font size to make the message readable in the projector.  It was a pain in the ass to select the projector background everytime via the menu in addition to selecting the exercise to start so exposing the setbackground would be good for getting to the shooting faster and in less steps.  I also needed to change the message location on the projector to where it made the most sense (for my Trap and CanToss it was best moved to a location near the bottom).

I agree with you on the using the targetGroup but when I tried adding the report card circles to the targetGroup but they did not show up for some reason so I went back to adding circles to the canvasGroup and then they appeared.

**Comment by phrack** [comment]
OK, the projector exercise API now lets you set the arena's background and show a message on all webcam feeds and the arena, all webcam feeds and not the arena, or all webcam feeds and the arena with a custom location, colors, and font for the arena version of the message.

I am not sure why adding to the target group didn't show the content. That's worth exploring a bit because it should work (it's been done in the past to show show where all shots landed on multiple targets on just one target).

**Comment by phrack** [comment]
Closing this since discussion seems to be dead.

**Pull request closed without merging**
