### PR TITLE
Very beta exposure adjustment control

### PR DESCRIPTION
**Pull request by cbdmaul**
phrack, please test before merge.  Exposure should auto adjust during autocalibration IF opencv/camera can do it on your system.  If it does nothing, that's okay too.  If it works but needs adjustment, that's acceptable as well.  If the devil himself comes out of your camera blame obama.

### CODE REVIEW

**Comment by phrack** [comment]
Interesting. It isn't doing anything because libv4l just throws an error log message stating it doesn't support setting the exposure. Still, I didn't expect libv4l to fail gracefully in this case. 

My observation so far suggests that if ShootOFF tried to change the exposure by bigger amounts it'd eventually run into the bug where v4l does actually change the exposure but you're stuck at essentially max or min exposure regardless of the actual value set.

**Comment by phrack** [comment]
Should merging this close #504?

**Comment by cbdmaul** [comment]
I added a comment on #504.  We could merge this and then future work will be on master.  I don't have anything off master anymore, and if it all works, no reason to keep it separate at this point.

**Comment by phrack** [comment]
Given your comment, I deleted your branch while merging.

**Pull request merged**
