### PR TITLE
checking for 32 or 64 bit OS for PS3Eye

### PR DESCRIPTION
**Pull request by ifly53e**
updated gradle and cameraType to support checking for OS architecture

### CODE REVIEW

**Comment by ifly53e** [comment]
I might have figured out the GitHubs...

**Comment by phrack** [comment]
I am going to make a few small tweaks now that it's merged, but looks good overall. Thanks!

**Comment by phrack** [comment]
https://github.com/phrack/ShootOFF/commit/fead628c361335f98ff5a14a933e9d70e824ed89

Shouldn't have broken anything, just lowering log levels and access modifiers where possible, making things immutable where possible, adding some missing nullness checks and log guards*, and running a code formatter.

*If you concatenate to a string in a log message you incur that penality even if the log message isn't written out because you don't have that log level set. Checking whether the log level is set first is faster on average in these cases since most people run at WARN.

**Comment by phrack** [comment]
I also changed the code in Main.java to only init the PS3Eye on Windows because it was, unsurprisingly, throwing exceptions on Linux.

**Comment by phrack** [comment]
@ifly53e I get this noisy output every time I run in my VM:

java.lang.UnsatisfiedLinkError: Unable to load library 'eyeCam64': Native library (win32-x86-64/eyeCam64.dll) not found in resource path (...)
    at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
    at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
    at com.sun.jna.Library$Handler.<init>(Library.java:147)
    at com.sun.jna.Native.loadLibrary(Native.java:502)
    at com.sun.jna.Native.loadLibrary(Native.java:481)
    at com.shootoff.camera.cameratypes.PS3EyeCamera.init(PS3EyeCamera.java:120)
    at com.shootoff.Main.start(Main.java:692)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
    at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
    at java.lang.Thread.run(Unknown Source)

I am guessing I get it because I didn't do the set-up steps documented at the top. I didn't do those steps because I don't have a PS3eye. I don't have a concrete suggestion, but it is annoying to get this noisy output every time even though I don't care about the PS3eye.

**Comment by ifly53e** [comment]
Did the dll make it into the build?

**Comment by phrack** [comment]
This is running from master not the build. Where does win32-x86-64 even come from? Is it working for you?

**Comment by ifly53e** [comment]
So I downloaded the latest nightly.  The dll's are in the build.  I ran ShootOFF from a non build environment box (64 bit windows).  I am getting an error that it can not find the 32bit dll.  That does not make any sense...I wonder what the system.properties call came back as?  Even though I am running in debug, I can not see the messages replayed by SLF4J so I am missing that debug information.

If running from a release, how can one see trace messages?

I do not get these errors on my production machine.

java -jar ShootOFF.jar -d
SLF4J: A number (6) of logging calls during the initialization phase have been intercepted and are

SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.

SLF4J: See also http://www.slf4j.org/codes.html#replay

2016-09-23 19:18:35 [JavaFX Application Thread] ERROR c.s.camera.cameratypes.PS3EyeCamera - 
PS3EyeCamera eyecam ULE, Can't find the eyeCamXX.dll or the Visual Studio Visual C++ runtime files are not installed:

java.lang.UnsatisfiedLinkError: Unable to load library 'eyeCam32': Native library (win32-
x86/eyeCam32.dll) not found in resource path ([file:/C:/Users/Tim/Desktop/nightly/ShootOFF.jar])

```
    at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)

    at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)

    at com.sun.jna.Library$Handler.<init>(Library.java:147)

    at com.sun.jna.Native.loadLibrary(Native.java:502)

    at com.sun.jna.Native.loadLibrary(Native.java:481)

    at com.shootoff.camera.cameratypes.PS3EyeCamera.init(PS3EyeCamera.java:125)

    at com.shootoff.Main.start(Main.java:692)

    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(Unknown Source)

    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(Unknown Source)

    at com.sun.javafx.application.PlatformImpl.lambda$null$173(Unknown Source)

    at java.security.AccessController.doPrivileged(Native Method)

    at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(Unknown Source)

    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)

    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)

    at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source)

    at java.lang.Thread.run(Unknown Source)
```

2016-09-23 19:18:36 [JavaFX Application Thread] INFO  de.dfki.lt.tools.tokenizer.JTok - loading language resources for en from jtok/en

2016-09-23 19:18:37 [JavaFX Application Thread] INFO  de.dfki.lt.tools.tokenizer.JTok - loading language resources for en from jtok/en

2016-09-23 19:18:37 [JavaFX Application Thread] INFO  com.shootoff.Main - Error reporting has been disabled.

2016-09-23 19:18:38 [Plugin Watcher] DEBUG c.s.plugins.engine.PluginEngine - Starting to watch plugins directory

2016-09-23 19:18:39 [JavaFX Application Thread] DEBUG com.shootoff.camera.CameraManager - starting camera thread Webcam 0

2016-09-23 19:23:20 [Plugin Watcher] DEBUG c.s.plugins.engine.PluginEngine - Stopped watching plugins directory

2016-09-23 19:23:20 [Shot detection Webcam 0 com.shootoff.camera.shotdetection.JavaShotDetector] WARN  com.shootoff.camera.CameraManager - Invalid frame yielded from Webcam 0

**Comment by ifly53e** [comment]
Ok...my error is what it looks like when shootoff is run with 32bit java on a 64bit machine.

Running 64bit java on a 64bit machine did not give any errors and the camera came up.

**Comment by ifly53e** [comment]
Maybe we put in a system.properties("sun.arch.data.model") check to go along with the "os.arch" check to prevent this.

**Pull request merged**
