### PR TITLE
get eyecam.dll into the build

### PR DESCRIPTION
**Pull request by ifly53e**
created a copy task and made fxJar depend on it

### CODE REVIEW

**Comment by ifly53e** [comment]
I must not have made the correct changes.  The latest nightly does not have the eyecam.dll in it...

**Comment by phrack** [comment]
This fixes it: https://github.com/phrack/ShootOFF/commit/fcab7425b66ef1aa07f9a6e7f2cfedf01e317496.

You forgot that the builder server runs Linux and Linux file systems are case sensitive.

**Comment by ifly53e** [comment]
ugh...alright.  Thanks.

**Comment by phrack** [comment]
What bitness is this DLL anyway?  We probably need a 32-bit version and a 64-bit version since the Java website has a bad habit of pushing 32-bit JREs even to 64-bit browsers and technical users will definitely want 64-bit.

Alternatively, add a bitness check and don't even try to initialize the camera if the JRE bitness does not match the DLL one.

**Comment by cbdmaul** [comment]
If the bitness doesn't match, won't it throw a UnsatisfiedLinkError?

I was going to test on the intel compute stick which is 32bit OS so I can test it later.

**Comment by ifly53e** [comment]
I compiled as 64 bit.

I can compile a 32 bit version.

**Comment by ifly53e** [comment]
The nightly I downloaded last night did not have the eyeCam.dll file in it.  Not sure why since my grade build had it.

**Comment by ifly53e** [comment]
It also appears that slf4j is not replaying my debug messages when the jar is run outside of eclipse.  How can I get them back?

**Comment by phrack** [comment]
It will throw an exception with a bitness mismatch, but I can't recall exactly what one.

Typically thing to do is include both bitnesses with slightly different names (put the bitness in the name), then check System.getProperty("os.arch"). If it's i386, i686, or x86 load the 32 bit one. If it's amd64 or x86_64, load the 64 bit one. Otherwise, gracefully fail.

**Comment by phrack** [comment]
The DLL is not in the build because we have to add it here: https://github.com/phrack/ShootOFF/blob/master/build.gradle#L258.

**Comment by cbdmaul** [comment]
Are you adding the "-d" parameter for debugging?

**Comment by ifly53e** [comment]
I use java -jar ShootOFF.jar -d
I see other debug messages, just not the ones that are being hidden during initialization by slf4j and not being replayed (the logger.debug messages in my cameratype for the PS3Eye)

**Pull request merged**
