### PR TITLE
Space Invaders

### PR DESCRIPTION
**Pull request by ifly53e**
I need some help testing this. I am experiencing some intermittent delays like my system is caching something.  I think it occurs around the time when I am using setRate to change all of the targets animation rates (but I am not sure).  What happens is that there is a delay when the aliens freeze, and then the aliens all move to where they were supposed to be if there was no delay.  Not sure if it is my system or the code.
By the way, if you think that there is a better way to implement this, I am all ears.  Thanks.

This projector exercise is an adaptation of Space Invaders, the video game from the 80's.  So it turns out that the moving blaster canon has malfunctioned and you have to shoot the aliens with your laser trainer. Who would have thought the aliens are vulnerable to 5mw of red light...
The top row of aliens are worth 15 points.  The middle two rows are worth 10 points.  The  bottom two rows are worth 5 points. The UFO is worth 20 points.  Firing and not hitting anything will take away 1 point per shot.  Win the game by hitting all of the aliens as fast as you can but beware...the aliens will speed up when they feel like they are threatened.  If the aliens hit the barriers at the bottom of the screen, the game is over and the world as you know it will cease to exist...until you press the reset button.

### CODE REVIEW

**Comment by phrack** [comment]
Some general code review comments:
- This class has a ton of state for an exercise. You might want to try to spin off some of its operations into another class. The internal classes also could be their own classes instead of internal to make this source file shorter.
- Some of the fields like MAX_TARGETS and clip don't have access modifiers, which defaults to package. Not sure if this is what you wanted.
- Most of your ArrayLists would have faster as HashSets (we have this same problem in a few places in ShootOFF's core, slowing fixing it here and there). ArrayList should be used if order matters and if you need dupes of an object in the list, otherwise a HashSet is typically faster in every way.
- Boundary is misspelled as boundry.  
- On line 165 you set the font color to black no matter what the condition is. Why have the condition at all? Same thing at 522.
- On 237, 239, and 241 you are comparing strings with ==. You need to use .equals, the most robust way would be "one half".equals(theScale) that way the check works right even if theScale is null for some reason. The follow up if blocks look like they should be else blocks instead of separate if statements because all of these checks are happening every time for no reason I can discern.
- You should replace (boundryHolder != b.targetLeft.getPosition().getX()) with something like Math.abs(boundryHolder - b.targetLeft.getPosition().getX()) > .0001 because the way you're checking for floating point equality on line 348 is buggy if you run into precision issues (and you easily can). 
- There is never a valid reason to call System.gc(); as in line 578. In fact, according to the JVM spec it's not even required to do anything. 
- Many file systems (Mac/Linux) are case sensitive, thus this will cause failures: new File("targets/UFO.target") on line 139. You named the file on the filesystem "ufo.target", because of the capitalization differences the file on line 139 does not exist on case-sensitive file systems.
- Just like your previous exercise, this one has too many resolution dependencies. It doesn't even work on resolutions that are smaller than you anticipated (which ARE valid projector resolutions) because the aliens start off-screen and therefore know to not move based on your conditions for moving them. We already give you everything you need to determine the arena resolution, you should use that information to decide how many aliens you will use.

My machine never got the slow down you mentioned, but there is enough clean-up to do here that a cause may become more clear later.

**Comment by ifly53e** [comment]
Thanks for the comments.  I will work on them.

Did you reject the change to the spriteAnimation class as well?  You agreed
to that earlier via reddit..

**Comment by phrack** [comment]
Pull requests are all or nothing, I can't accept just the spriteAnimation changes without also accepting the entire exercise and everything else.

**Comment by phrack** [comment]
PS. On that note, I think setFrame should probably be named setVisibleFrame as that seems more descriptive of what the method actually does.

**Comment by ifly53e** [comment]
"Visible" has close ties to setVisible which might be confusing.  For example, one could set the current frame of the animation that is not shown on the screen yet.  How about setCurrentFrame?

**Comment by phrack** [comment]
Yea, that makes sense. I mostly wanted to avoid conntations with changing a frame at a particular index to something else, which is how this method name would be taken with a Collections class.

**Pull request closed without merging**
